// lib/exports/punchLogs.js
import {
  BRANDING,
  fetchCurrentUser,
  extractUserInfo,
  calculateSummaryStats,
  wrapCSV,
  drawBizBuddyLogo,
  formatUserForFilename,
  getTimestampForFilename,
  getFormattedTimestamp,
  jsPDF,
  autoTable,
} from "./_shared.js";

// ==========================================
// PUNCH LOGS EXPORT FUNCTIONS
// ==========================================

/**
 * Exports punch logs data as CSV with professional header and branding
 * @param {Object} params - Export parameters
 * @param {Array} params.data - Array of punch log records to export
 * @param {Object} params.user - (Optional) User object, if not provided, will fetch from /get-user-details
 * @param {string} params.filename - (Optional) Custom filename
 * @returns {Object} Result object with success flag and filename
 */
export const exportPunchLogsCSV = async ({ data, user = null, filename = null, timezone = "UTC" }) => {
  if (!data || data.length === 0) {
    throw new Error("No data to export");
  }

  try {
    // Fetch user data if not provided
    const userData = user || await fetchCurrentUser();

    const userInfo = extractUserInfo(userData);
    const stats = calculateSummaryStats(data);
    const generatedAt = getFormattedTimestamp();
    const userForFile = formatUserForFilename(userData);
    const timestamp = getTimestampForFilename();

    // ===== BUILD CLEAN HEADER =====
    const headerRows = [
      [`${BRANDING.companyName.toUpperCase()} - PUNCH LOGS REPORT`],
      [BRANDING.tagline],
      [""],
    ];

    // ===== METADATA SECTION (Two-column layout) =====
    const metadataRows = [
      ["REPORT INFORMATION", "", "", "", "SUMMARY STATISTICS"],
      [""],
      ["Company:", userInfo.companyName, "", "", "Total Records:", stats.totalRecords],
      ["Employee Name:", userInfo.fullName, "", "", "Active Punches:", stats.activeCount],
      ["Username:", userInfo.username, "", "", "Completed Punches:", stats.completedCount],
      ["Email:", userInfo.email, "", "", ""],
      ["User ID:", userInfo.userId, "", "", "Total Work Hours:", `${stats.totalHours} hrs`],
      ["", "", "", "", "Total Overtime:", `${stats.totalOT} hrs`],
      ["Report Generated:", generatedAt, "", "", "Total Coffee Breaks:", `${stats.totalCoffeeBreak} hrs`],
      ["Generated By:", userInfo.fullName, "", "", "Total Lunch Breaks:", `${stats.totalLunchBreak} hrs`],
      ["", "", "", "", "Total Late Hours:", `${stats.totalLateHours} hrs`],
      [""],
      [""],
    ];

    // ===== TABLE HEADER =====
    const tableHeaderRows = [
      ["PUNCH LOGS DETAIL"],
      [""],
    ];

    const tableHeader = [
      "ID",
      "Date",
      "Time In",
      "Time Out",
      "Duration (hrs)",
      "Coffee Break (hrs)",
      "Lunch Break (hrs)",
      "Overtime (hrs)",
      "OT Status",
      "Late Hours (hrs)",
      "Period Hours (hrs)",
      "Status",
    ];

    // ===== TABLE DATA ROWS =====
    const tz = timezone || "UTC";
    const tableRows = data.map((log) => [
      log.id || "—",
      log.timeIn ? new Date(log.timeIn).toLocaleDateString("en-US", { year: "numeric", month: "2-digit", day: "2-digit", timeZone: tz }) : "—",
      log.timeIn
        ? new Date(log.timeIn).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", hour12: true, timeZone: tz })
        : "—",
      log.timeOut
        ? new Date(log.timeOut).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", hour12: true, timeZone: tz })
        : "—",
      log.duration || "0.00",
      log.coffeeMins || "0.00",
      log.lunchMins || "0.00",
      log.otHours || "0.00",
      log.otStatus || "—",
      log.lateHours || "0.00",
      log.periodHours || "0.00",
      log.status ? "Active" : "Completed",
    ]);

    // ===== FOOTER =====
    const footerRows = [
      [""],
      [""],
      [`${BRANDING.companyName} | ${BRANDING.tagline}`],
      [`© ${new Date().getFullYear()} | All Rights Reserved`],
    ];

    // ===== COMBINE ALL ROWS =====
    const allRows = [
      ...headerRows.map((row) => row.map(wrapCSV)),
      ...metadataRows.map((row) => row.map(wrapCSV)),
      ...tableHeaderRows.map((row) => row.map(wrapCSV)),
      tableHeader.map(wrapCSV),
      ...tableRows.map((row) => row.map(wrapCSV)),
      ...footerRows.map((row) => row.map(wrapCSV)),
    ];

    const csvContent = allRows.map((row) => row.join(",")).join("\r\n");

    // ===== CREATE AND DOWNLOAD =====
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    const finalFilename = filename || `BizBuddy_PunchLogs_${userForFile}_${timestamp}.csv`;
    link.download = finalFilename;
    link.click();
    URL.revokeObjectURL(url);


    return { success: true, filename: finalFilename };
  } catch (error) {
    console.error("❌ CSV export failed:", error);
    throw error;
  }
};

// ==========================================
// PDF EXPORT FUNCTIONS
// ==========================================

/**
 * Exports punch logs data as professional PDF with branding
 * @param {Object} params - Export parameters
 * @param {Array} params.data - Array of punch log records to export
 * @param {Object} params.user - (Optional) User object, if not provided, will fetch from /get-user-details
 * @param {string} params.filename - (Optional) Custom filename
 * @returns {Object} Result object with success flag and filename
 */
export const exportPunchLogsPDF = async ({ data, user = null, filename = null, timezone = "UTC" }) => {
  if (!data || data.length === 0) {
    throw new Error("No data to export");
  }

  try {
    // Fetch user data if not provided
    const userData = user || await fetchCurrentUser();

    const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    const userInfo = extractUserInfo(userData);
    const stats = calculateSummaryStats(data);
    const generatedAt = getFormattedTimestamp();
    const userForFile = formatUserForFilename(userData);
    const timestamp = getTimestampForFilename();

    // ===== HEADER SECTION =====
    let yPos = 15;

    // Draw the actual BizBuddy logo
    await drawBizBuddyLogo(doc, 15, yPos);

    doc.setTextColor(...BRANDING.colors.primary);
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("PUNCH LOGS REPORT", pageWidth / 2, yPos + 6, { align: "center" });

    doc.setTextColor(...BRANDING.colors.dark);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text("Employee Time Management System", pageWidth / 2, yPos + 11, { align: "center" });

    doc.setTextColor(...BRANDING.colors.light);
    doc.setFontSize(8);
    doc.text(`Generated: ${generatedAt}`, pageWidth - 15, yPos + 3, {
      align: "right",
    });

    yPos += 18;
    doc.setDrawColor(...BRANDING.colors.primary);
    doc.setLineWidth(0.8);
    doc.line(15, yPos, pageWidth - 15, yPos);

    // ===== EMPLOYEE INFO SECTION =====
    yPos += 6;
    doc.setFillColor(...BRANDING.colors.primaryLight);
    doc.roundedRect(15, yPos, pageWidth - 30, 24, 2, 2, "F");

    doc.setTextColor(...BRANDING.colors.primary);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("EMPLOYEE INFORMATION", 20, yPos + 5);

    yPos += 9;
    doc.setTextColor(...BRANDING.colors.dark);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("Company:", 20, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(userInfo.companyName, 50, yPos);

    yPos += 5;
    doc.setFont("helvetica", "bold");
    doc.text("Employee:", 20, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(`${userInfo.fullName} | ${userInfo.username}`, 50, yPos);

    yPos += 5;
    doc.setFont("helvetica", "bold");
    doc.text("Email:", 20, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(userInfo.email, 50, yPos);

    // ===== TABLE SECTION =====
    yPos += 12;

    const tableHeaders = [
      "ID",
      "Date",
      "Time In",
      "Time Out",
      "Duration",
      "Coffee",
      "Lunch",
      "OT",
      "OT Status",
      "Late",
      "Status",
    ];

    const tz = timezone || "UTC";
    const tableData = data.map((log) => [
      log.id || "—",
      log.timeIn ? new Date(log.timeIn).toLocaleDateString("en-US", { year: "numeric", month: "2-digit", day: "2-digit", timeZone: tz }) : "—",
      log.timeIn
        ? new Date(log.timeIn).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", hour12: true, timeZone: tz })
        : "—",
      log.timeOut
        ? new Date(log.timeOut).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", hour12: true, timeZone: tz })
        : "—",
      `${log.duration || "0.00"}h`,
      `${log.coffeeMins || "0.00"}h`,
      `${log.lunchMins || "0.00"}h`,
      `${log.otHours || "0.00"}h`,
      log.otStatus || "—",
      `${log.lateHours || "0.00"}h`,
      log.status ? "Active" : "Done",
    ]);

    autoTable(doc, {
      head: [tableHeaders],
      body: tableData,
      startY: yPos,
      margin: { left: 15, right: 15 },
      styles: {
        fontSize: 8,
        cellPadding: 2.5,
        lineColor: [200, 200, 200],
        lineWidth: 0.1,
        textColor: BRANDING.colors.dark,
      },
      headStyles: {
        fillColor: BRANDING.colors.primary,
        textColor: BRANDING.colors.white,
        fontStyle: "bold",
        halign: "center",
        fontSize: 8,
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
      columnStyles: {
        0: { cellWidth: 30, halign: "left" },
        1: { cellWidth: 23, halign: "center" },
        2: { cellWidth: 20, halign: "center" },
        3: { cellWidth: 20, halign: "center" },
        4: { cellWidth: 18, halign: "right" },
        5: { cellWidth: 16, halign: "right" },
        6: { cellWidth: 16, halign: "right" },
        7: { cellWidth: 16, halign: "right" },
        8: { cellWidth: 25, halign: "center" },
        9: { cellWidth: 16, halign: "right" },
        10: { cellWidth: 20, halign: "center" },
      },
      didDrawCell: (data) => {
        if (data.column.index === 7 && data.row.index >= 0) {
          const otValue = parseFloat(data.cell.text[0]);
          if (otValue > 0) {
            doc.setTextColor(...BRANDING.colors.primary);
            doc.setFont("helvetica", "bold");
          }
        }
        if (data.column.index === 10 && data.cell.text[0] === "Active") {
          doc.setTextColor(...BRANDING.colors.primary);
          doc.setFont("helvetica", "bold");
        }
      },
    });

    // ===== FOOTER ON ALL PAGES =====
    const pageCount = doc.internal.getNumberOfPages();
    const currentYear = new Date().getFullYear();

    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);

      doc.setDrawColor(...BRANDING.colors.light);
      doc.setLineWidth(0.3);
      doc.line(15, pageHeight - 15, pageWidth - 15, pageHeight - 15);

      // Left: BizBuddy branding
      doc.setTextColor(...BRANDING.colors.dark);
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.text(`${BRANDING.companyName} | ${BRANDING.tagline}`, 15, pageHeight - 11);

      doc.setFont("helvetica", "normal");
      doc.setTextColor(...BRANDING.colors.light);
      doc.text(`© ${currentYear}`, 15, pageHeight - 7);

      // Center: Requestor info
      doc.setTextColor(...BRANDING.colors.dark);
      doc.setFontSize(7);
      doc.text(
        `Requestor: ${userInfo.fullName} | ${userInfo.email}`,
        pageWidth / 2,
        pageHeight - 9,
        { align: "center" }
      );

      // Right: Page number
      doc.setTextColor(...BRANDING.colors.light);
      doc.setFontSize(8);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - 15, pageHeight - 9, {
        align: "right",
      });
    }

    // ===== SAVE THE PDF =====
    const finalFilename = filename || `BizBuddy_PunchLogs_${userForFile}_${timestamp}.pdf`;
    doc.save(finalFilename);

    return { success: true, filename: finalFilename };
  } catch (error) {
    console.error("❌ PDF export failed:", error);
    throw error;
  }
};

// ==========================================
// GRID / PAYROLL CSV EXPORT (v2 template)
// ==========================================

/**
 * Exports punch logs as a DayCare payroll grid CSV.
 * Layout: rows = employees, columns = dates with AM / Regular / PM hour breakdown.
 * Matches the punchLogs_v2.csv template format.
 *
 * @param {Object} params
 * @param {Array}  params.data     - Processed punch log records (must include driverAideAMHours, regularHoursForLog, driverAidePMHours)
 * @param {Object} params.user     - (Optional) User object; fetched automatically if omitted
 * @param {string} params.filename - (Optional) Custom filename
 */
export const exportPunchLogsCSV_v2 = async ({ data, user = null, filename = null, timezone = "UTC" }) => {
  if (!data || data.length === 0) throw new Error("No data to export");

  try {
    const userData    = user || await fetchCurrentUser();
    const userInfo    = extractUserInfo(userData);
    const userForFile = formatUserForFilename(userData);
    const timestamp   = getTimestampForFilename();

    // ── Group logs by calendar date ──────────────────────────────────────────
    const tz = timezone || "UTC";
    const byDate = {};
    for (const log of data) {
      const date = log.timeIn ? new Date(log.timeIn).toLocaleDateString("en-CA", { timeZone: tz }) : null;
      if (!date) continue;
      if (!byDate[date]) byDate[date] = log; // one log per day expected
    }
    const dates = Object.keys(byDate).sort();

    // ── Determine employee type from punch types present ─────────────────────
    const punchTypes = data.map((l) => l.punchType).filter(Boolean);
    const hasDA = punchTypes.some((p) => p !== "REGULAR");
    const type = !hasDA
      ? "Staff"
      : punchTypes.includes("DRIVER_AIDE") || punchTypes.includes("DRIVER_AIDE_AM")
        ? "Driver"
        : "Aide";

    // ── Row 1: date number header ────────────────────────────────────────────
    // Structure: [blank, blank, blank, blank, dayNum, blank, blank, dayNum, ...totals...notes]
    const dateRow = ["", "", "", ""];
    for (const date of dates) {
      dateRow.push(new Date(date).getDate(), "", "");
    }
    dateRow.push("Total Hours", "", "", "TR", "SL", "Total", "", "TR - Training");

    // ── Row 2: column label header ───────────────────────────────────────────
    const colRow = ["", "ID", "Name of Employee", "Type"];
    for (let i = 0; i < dates.length; i++) {
      colRow.push("Driver Aide AM", "Regular", "Driver Aide PM");
    }
    colRow.push("Driver Aide AM", "Regular", "Driver Aide PM", "", "", "", "", "SL - Sick Leave");

    // ── Data row ─────────────────────────────────────────────────────────────
    let totalAM = 0, totalReg = 0, totalPM = 0;
    const dataRow = ["", userInfo.userId, userInfo.fullName, type];

    for (const date of dates) {
      const log  = byDate[date];
      const isDA = ["DRIVER_AIDE", "DRIVER_AIDE_AM", "DRIVER_AIDE_PM"].includes(log.punchType);

      const amH  = isDA && log.driverAideAMHours  != null ? parseFloat(log.driverAideAMHours)  : 0;
      const regH = isDA && log.regularHoursForLog != null
        ? parseFloat(log.regularHoursForLog)
        : parseFloat(log.duration) || 0;
      const pmH  = isDA && log.driverAidePMHours  != null ? parseFloat(log.driverAidePMHours)  : 0;

      totalAM  += amH;
      totalReg += regH;
      totalPM  += pmH;

      dataRow.push(
        amH  > 0 ? amH.toFixed(2)  : "",
        regH > 0 ? regH.toFixed(2) : "",
        pmH  > 0 ? pmH.toFixed(2)  : ""
      );
    }

    const grandTotal = totalAM + totalReg + totalPM;
    dataRow.push(
      totalAM  > 0 ? totalAM.toFixed(2)  : "",
      totalReg > 0 ? totalReg.toFixed(2) : "",
      totalPM  > 0 ? totalPM.toFixed(2)  : "",
      "", // TR (Training — left blank for manual entry)
      "", // SL (Sick Leave — left blank for manual entry)
      grandTotal > 0 ? grandTotal.toFixed(2) : ""
    );

    // ── Total row ─────────────────────────────────────────────────────────────
    const totalRow = ["Total", "", "", ""];
    for (let i = 0; i < dates.length; i++) totalRow.push("", "", "");
    totalRow.push(
      totalAM  > 0 ? totalAM.toFixed(2)  : "",
      totalReg > 0 ? totalReg.toFixed(2) : "",
      totalPM  > 0 ? totalPM.toFixed(2)  : "",
      "", "",
      grandTotal > 0 ? grandTotal.toFixed(2) : ""
    );

    // ── Remarks section (matches template) ────────────────────────────────────
    const remarksRows = [
      [""],
      [""],
      ["", "", "Remarks", "Color"],
      ["", "", "Aide",          "Blue"],
      ["", "", "Driver",        "Red"],
      ["", "", "Program Hours", "Black"],
      ["", "", "Absent",        "Orange"],
      ["", "", "Holiday",       "Yellow"],
    ];

    // ── Assemble & download ───────────────────────────────────────────────────
    const allRows = [dateRow, colRow, dataRow, totalRow, ...remarksRows];
    const csvContent = allRows.map((row) => row.map(wrapCSV).join(",")).join("\r\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url  = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href  = url;
    const finalFilename = filename || `BizBuddy_PunchLogs_Grid_${userForFile}_${timestamp}.csv`;
    link.download = finalFilename;
    link.click();
    URL.revokeObjectURL(url);

    return { success: true, filename: finalFilename };
  } catch (error) {
    console.error("❌ Grid CSV export failed:", error);
    throw error;
  }
};

// ==========================================
// COMBINED EXPORT UTILITY
// ==========================================

/**
 * Quick utility to export both CSV and PDF simultaneously
 * @param {Object} params - Export parameters
 * @param {Array} params.data - Array of punch log records to export
 * @param {Object} params.user - (Optional) User object, if not provided, will fetch from /get-user-details
 * @returns {Object} Result object with both export results
 */
export const exportBoth = async ({ data, user = null }) => {
  try {
    // Fetch user data once if not provided
    const userData = user || await fetchCurrentUser();

    const csvResult = await exportPunchLogsCSV({ data, user: userData });
    const pdfResult = await exportPunchLogsPDF({ data, user: userData });

    return {
      success: true,
      csv: csvResult,
      pdf: pdfResult,
    };
  } catch (error) {
    console.error("Export error:", error);
    return {
      success: false,
      error: error.message,
    };
  }
};
